### PR TITLE
Create bip9-cn.md

### PR DESCRIPTION
**Pull request by ShiliangHuang**

### CODE REVIEW

**Comment by zander** [comment]
This is great, thank you!

The page should show up minutes after I merge.

**Comment by kFTY** [comment]
@zander , https://blocksizeproposals.github.io/bip9-cn.md is not displaying correctly. 
This should be a solution:
in
`/lib/jekyll/convertible.rb `
change
`self.content = File.read(File.join(base, name))`
to
`self.content = File.read(File.join(base, name), :encoding => "utf-8")`

**Comment by zander** [comment]
@kFTY try using this url;
https://blocksizeproposals.github.io/bip9-cn

apart from some minor issues in markup, it looks good to me.

**Comment by kFTY** [comment]
You are right, I just used wrong URL... Thanks

**Pull request merged**
